---
# title: "tech_info"
output: html_fragment
---


## Overview  

This document provides additional technical information associated with the prioritization and stand summary tools. Content within the Climate-wise Reforestation Toolkit was developed by Zack Steel, Marc Meyer, Amarina Wuenschel, Steve Ostoja, and Malcolm North with funding provided by the US Forest Service.  

***

## Data processing & sources  

Forest biomass loss  
* Calculated as the percentage change from 2012 to 2016 estimates  
* Original data from the [LEMMA lab at Oregon State University](https://lemma.forestry.oregonstate.edu/) and the USDA Forest Service Region 5.  

Climate Water Deficit (CWD)  
* 1981-2010 average potential minus actual evapotranspiration -
* Data layer developed as part of the California Basin Characterization Model and acquired from [California Climate Commons](http://climate.calcommons.org/variable/climatic-water-deficit)  

High-severity Fire Core  
* Defined as areas within high-severity patches that are a minimum of 200m away from a lower severity edge (i.e. areas far from living tree seed sources).  
* Data source: [USDA Forest Service Geospatial Data](https://www.fs.usda.gov/detail/r5/landmanagement/gis/?cid=STELPRDB5327833)  

Wildland urban Interface (WUI)  
* Data source: Cal Fire [Fire and Resource Assessment Program](https://frap.fire.ca.gov/mapping/gis-data/)  

Recreation Areas  
* Data Source: [USDA Forest Service Geospatial Data](https://www.fs.usda.gov/detail/r5/landmanagement/gis/?cid=STELPRDB5327833)   

Spotted Owl Protected Activity Centers (PACs)  
* Data Source: [Data Basin](https://databasin.org/datasets/ee608449-2619-4c72-816c-0a75b1801015)  

Fisher Core Habitat areas  
* Data Source: [Data Basin](https://databasin.org/datasets/ba0ca69e7e024cfdbf816a33b64238a5)  

Mechanical Treatments Opportunities  
* We define areas available for mechanical operations using scenarios B ("Moderate constraints") and D ("Fewer constraints") from [North et al. 2015](https://academic.oup.com/jof/article/113/1/40/4599106). Scenario B can be considered moderately strict in its adherence to current standards and guides, and allows operations on <35% slopes, within 1,000 ft of existing roads or within 2,000 ft where more valuable timber exists to defray costs. Scenario D includes all forests <35% slope within 2,000 ft regardless of timber value, and all forests 35-50% slope within 1,000 ft of existing roads. Additionally, this and all scenarios (A-D), limit operations to previously forested lands, areas outside of wilderness and roadless areas, and areas outside of special administrative designations.  
* Data Source: [USDA Forest Service Geospatial Data](https://www.fs.usda.gov/detail/r5/landmanagement/gis/?cid=STELPRDB5327833)  

***

## Prioritization calculation  

Reforestation prioritization is calculated in three steps:  

1) The forested area considered is limited to national forest ownership within an area of interest, areas of mechanical treatment opportunity (scenario B), and areas where mortality was significant. The area of interest, and threshold for significant mortality or reforestation need is defined by the user. Areas that do not meet the above criteria are masked out of the calculation.  

2) For each 1 hectare pixel, all data layers are summed to get a continous absolute priority level. Most data layers are binary with values of 0 or 1 (e.g. spotted owl PAC). Continuous data layers (forest biomass loss and CWD) are scaled with a maximum of 1 prior to summation. With the exception of the biomass loss layer, a user can weight each data layer to scale it's influence on prioritization. For example, a weight of zero means a data layer has no effect on prioritization. A weight of -1 or 1, will give equal weight to a given data layer as the biomass loss layer, with the weighted layer reducing or increasing priority, respectively.  

3) Raw priority values are re-classified to 3 relative levels of priority: low, moderate, and high. For each calculation, a third of the area considered in need of reforestation is partitioned to each priority level.  


